# Generated by Django 5.2.6 on 2025-09-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_image_review_created_at_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
