# Generated by Django 5.2.6 on 2025-09-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_resettoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='token',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
